# Generated by Django 3.2.15 on 2022-08-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='N/A', max_length=254),
        ),
    ]
