# Generated by Django 3.2.15 on 2022-08-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
