# Generated by Django 3.2.15 on 2022-09-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
